version: "3"
services:
  auth-service:
    build: ./backend/auth-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth
  gateway:
    image: express-gateway
    depends_on:
      - auth-service
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
